version: '3.1'

services:

  # Wordpress
  wordpress:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - 7500:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: docker_wp_config
    volumes:
      - ./public:/var/www/html

  # MySql
  mysql:
    image: mysql:5.7
    ports:
      - 7501:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_wp_config

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - 7502:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  wordpress:
  mysql:
  phpmyadmin:

